Introduce Nix development flake
TraceMachina/turbo-cache pull request #330
Opened 2023-10-20 18:14 UTC by aaronmondal

Provide a mostly self-contained development environment automatically sets up tooling like Cargo and Bazel via nix.

This makes it easy for nix users to contribute to our project and enables future work on reproducible release binaries and containers.

2023-10-20 18:15 UTC, aaronmondal commented
cc @blakehatch I can't add you as reviewer for some reason

2023-10-20 18:48 UTC, allada requested changes
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/330)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @aaronmondal and @MarcusSorealheis)

___
*[`flake.nix` line 10 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/330#-NhDNIcF6DJW6NBfmkGV:-NhDNIcF6DJW6NBfmkGW:bg9so1) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/af44756bd6ca16c16569f672b6f9847d773ce438/flake.nix#L10)):*
> ```Nix
>   outputs = inputs@{ nixpkgs, flake-parts, ... }:
>     flake-parts.lib.mkFlake { inherit inputs; } {
>       systems = [ "x86_64-linux" ];
> ```

What about mac, windows, ARM?
___
*[`.github/workflows/nix.yaml` line 14 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/330#-NhDNZbm4VNhYlnvON8R:-NhDNZbm4VNhYlnvON8S:boza02m) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/af44756bd6ca16c16569f672b6f9847d773ce438/.github/workflows/nix.yaml#L14)):*
> ```YAML
> jobs:
>   nix-bazel:
>     runs-on: ubuntu-latest
> ```

nit: Lets pin specific versions.
___
*[`.github/workflows/nix.yaml` line 39 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/330#-NhDNbfV22lFvOIiu5Sv:-NhDNbfV22lFvOIiu5Sw:b-5v3gaq) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/af44756bd6ca16c16569f672b6f9847d773ce438/.github/workflows/nix.yaml#L39)):*
> ```YAML
>           bash -c "bazel test ..."
>   nix-cargo:
>     runs-on: ubuntu-latest
> ```

nit: ditto.
___
*[`tools/wrapped-bazel.nix` line 18 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/330#-NhDNwI61X5rE5lQWMDo:-NhDNwI61X5rE5lQWMDp:b-gnwreo) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/af44756bd6ca16c16569f672b6f9847d773ce438/tools/wrapped-bazel.nix#L18)):*
> ```Nix
> ]]; then
>     ${bazel}/bin/bazel $1 \
>         --action_env=OPENSSL_INCLUDE_DIR="${openssl.dev}/include" \
> ```

nit: just put this into the `.bazelrc` something like:
```
build:nix --action_env=OPENSSL_INCLUDE_DIR
build:nix --action_env=OPENSSL_LIB_DIR
```

Then just inject those enviorns to bazel.

Then run bazel as `"$@" --config nix`


<!-- Sent from Reviewable.io -->

2023-10-20 18:55 UTC, aaronmondal commented
*[`flake.nix` line 10 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/330#-NhDNIcF6DJW6NBfmkGV:-NhDQawJ6Dd04QjpFXkh:bivi55k) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/af44756bd6ca16c16569f672b6f9847d773ce438/flake.nix#L10)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

What about mac, windows, ARM?
</blockquote></details>

Native Windows doesn't work with Nix. WSL2 usually defaults to Ubuntu. As long as we don't depend on CUDA the current workflows should cover that.

I can't test Mac at the moment. I propose to postpone this until we have a way to debug those builds on Mac x86_64 and ARM.


<!-- Sent from Reviewable.io -->

2023-10-20 18:56 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/330#-:-NhDRYJw11A-hR8wpeeG:bnfp4nl)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @aaronmondal and @MarcusSorealheis)

___
*[`flake.nix` line 10 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/330#-NhDNIcF6DJW6NBfmkGV:-NhDRUvU3eqGZTUEbxmm:bw0aljb) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/af44756bd6ca16c16569f672b6f9847d773ce438/flake.nix#L10)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Native Windows doesn't work with Nix. WSL2 usually defaults to Ubuntu. As long as we don't depend on CUDA the current workflows should cover that.

I can't test Mac at the moment. I propose to postpone this until we have a way to debug those builds on Mac x86_64 and ARM.
</blockquote></details>

Yeah sounds good :-)


<!-- Sent from Reviewable.io -->

2023-10-20 19:04 UTC, aaronmondal commented
*[`tools/wrapped-bazel.nix` line 18 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/330#-NhDNwI61X5rE5lQWMDo:-NhDRH9Z7aYYsfSQbsso:badu452) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/af44756bd6ca16c16569f672b6f9847d773ce438/tools/wrapped-bazel.nix#L18)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: just put this into the `.bazelrc` something like:
```
build:nix --action_env=OPENSSL_INCLUDE_DIR
build:nix --action_env=OPENSSL_LIB_DIR
```

Then just inject those enviorns to bazel.

Then run bazel as `"$@" --config nix`
</blockquote></details>

That doesn't work in this case because these paths are dynamically generated and the `.bazelrc` can't resolve `$SOMEVARIABLE`. We'd have to manually update these environment variables every time someone updates the flake. I had something like that at some point but it was too tedious to keep it in sync.


<!-- Sent from Reviewable.io -->

2023-10-20 19:40 UTC, merged

2023-10-22 14:32 UTC, allada reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/330)* status: 8 of 10 files reviewed, all discussions resolved

___
*[`tools/wrapped-bazel.nix` line 18 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/330#-NhDNwI61X5rE5lQWMDo:-NhMn7KwEjx_G_3Xagle:b1aoxvv) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/af44756bd6ca16c16569f672b6f9847d773ce438/tools/wrapped-bazel.nix#L18)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

That doesn't work in this case because these paths are dynamically generated and the `.bazelrc` can't resolve `$SOMEVARIABLE`. We'd have to manually update these environment variables every time someone updates the flake. I had something like that at some point but it was too tedious to keep it in sync.
</blockquote></details>

On the line above this, cant you just use:
`export OPENSSL_INCLUDE_DIR="${openssl.dev}/include"`

The `--action_env` will auto-pickup those environs.

?


<!-- Sent from Reviewable.io -->