Removed response message and set to empty string
TraceMachina/turbo-cache pull request #332
Opened 2023-10-20 21:29 UTC by blakehatch

Response message needs to just be an empty string as it shows on every failure for TWA.

Fixes #331

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

2023-10-20 22:21 UTC, allada requested changes
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/332)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @blakehatch)

*[a discussion](https://reviewable.io/reviews/TraceMachina/turbo-cache/332#-NhEAXh7BGpxLV5npLXi:-NhEAXh7BGpxLV5npLXj:b-wqtpqk) (no related file):*
I think there's some tests that also need to be modified.

___
___
*[`cas/scheduler/action_messages.rs` line 717 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/332#-NhEAQYN9XcVVs6dahWM:-NhEAQYN9XcVVs6dahWN:bngqxab) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/a3e7decad7353a3bb8b40091e7c9b3f8e5a83c47/cas/scheduler/action_messages.rs#L717)):*
> ```XML
>                     cached_result: false,
>                     status,
>                     message: RESPONSE_MESSAGE.to_string(),
> ```

nit: Please remove it down here too :-)
___
*[`cas/scheduler/action_messages.rs` line 727 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/332#-NhEAUUy74m9CdG8pG89:-NhEAUUz9wpOIfjsT3kL:b-rqxvo7) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/a3e7decad7353a3bb8b40091e7c9b3f8e5a83c47/cas/scheduler/action_messages.rs#L727)):*
> ```XML
>                 cached_result: true,
>                 status: Some(Status::default()),
>                 message: RESPONSE_MESSAGE.to_string(),
> ```

ditto.


<!-- Sent from Reviewable.io -->

2023-10-20 22:47 UTC, blakehatch reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/332)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @allada)

*[a discussion](https://reviewable.io/reviews/TraceMachina/turbo-cache/332#-NhEAXh7BGpxLV5npLXi:-NhEEJTA4fQU631x6ZER:b-4543fn) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I think there's some tests that also need to be modified.
</blockquote></details>

Yup removed a foo and a TODO message from worker_api_server_test

___
___
*[`cas/scheduler/action_messages.rs` line 727 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/332#-NhEAUUy74m9CdG8pG89:-NhEE8uE6wyCn4q8z-aM:bueams3) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/a3e7decad7353a3bb8b40091e7c9b3f8e5a83c47/cas/scheduler/action_messages.rs#L727)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Replaced with empty strings and removed original RESPONSE_MESSAGE as it was unused. 


<!-- Sent from Reviewable.io -->

2023-10-20 22:55 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

Can we also create a ticket to actually populate this and reference this PR?

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/332#-:-NhEI5uIC4HpLxttCDSi:bvkvq58)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @blakehatch)



<!-- Sent from Reviewable.io -->

2023-10-20 23:05 UTC, blakehatch reviewed
Yes referenced this PR in #333

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/332#-:-NhEKWen6HpYUGxUOAcA:b-s84n6k)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @blakehatch)



<!-- Sent from Reviewable.io -->

2023-10-22 09:21 UTC, chrisstaite-menlo commented
*[`cas/grpc_service/tests/worker_api_server_test.rs` line 336 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/332#-NhLg7KuBLMY6he70qUj:-NhLg7KuBLMY6he70qUk:b-uydm8n) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/5d60aeb3a4de9c1c985a7c9d018e4848f26d9eff/cas/grpc_service/tests/worker_api_server_test.rs#L336)):*
> ```XML
>                 status: Some(ProtoStatus {
>                     code: 9,
>                     message: String::new(),
> ```

This change doesn't look right, you didn't remove anything that says `foo`?


<!-- Sent from Reviewable.io -->

2023-10-23 19:27 UTC, blakehatch reviewed
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/332)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @allada and @chrisstaite-menlo)

___
*[`cas/grpc_service/tests/worker_api_server_test.rs` line 336 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/332#-NhLg7KuBLMY6he70qUj:-NhT-JbU9xa7Ci80iyhX:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/5d60aeb3a4de9c1c985a7c9d018e4848f26d9eff/cas/grpc_service/tests/worker_api_server_test.rs#L336)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

This change doesn't look right, you didn't remove anything that says `foo`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-24 16:14 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> Dismissed @chrisstaite-menlo from a discussion.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/332#-:-NhXSmRj1KdQXriy-bwg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @blakehatch)



<!-- Sent from Reviewable.io -->

2023-11-01 15:46 UTC, closed without merging