Add optimistic channels
TraceMachina/turbo-cache pull request #341
Opened 2023-10-25 23:01 UTC by aaronmondal

This variation on make_buf_channel_pair omits the EOF check. This works around the fact that S3 drops connections as soon as all data is sent or received.

Fixes #304 and fixes the same issue for non-oneshot cases where a similar issue occurred as well.

2023-10-25 23:14 UTC, MarcusSorealheis reviewed
My question is should these `ObjectStore` or `S3Store` . I'm torn because I don't want us to be wed to a vendor in the implementation on the one hand, but on the other hand the other object stores in the market tend to implement the S3 API because they are a leader. My hesitation feels a little nit picky and pedantic and can probably be deferred. 

Explicitly keeping S3 in the codebase as a store type is something we probably want to move away from.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/341#-:-Nhd65Bu-_9OyS1KWzPf:b-nb226g)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @allada)



<!-- Sent from Reviewable.io -->

2023-10-25 23:19 UTC, allada requested changes
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/341)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @aaronmondal)

___
*[`util/buf_channel.rs` line 58 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/341#-Nhd50TZ3A0Ncft8BGYL:-Nhd50TZ3A0Ncft8BGYM:b-twjjao) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/d8bf8c0670a8171beeecf58b4c1e4c033aa16f4f/util/buf_channel.rs#L58)):*
> ```XML
> /// the receiver can be trusted to handle failing streams this is safe to do.
> #[must_use]
> pub fn make_buf_channel_pair_optimistic_writer() -> (DropCloserWriteHalf, DropCloserReadHalf) {
> ```

Why not just add `.disable_eof_check(&mut self)` on the writer?
___
*[`util/buf_channel.rs` line 88 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/341#-Nhd7BfI4JsNT6zJKT4z:-Nhd7BfI4JsNT6zJKT5-:byf8xyc) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/d8bf8c0670a8171beeecf58b4c1e4c033aa16f4f/util/buf_channel.rs#L88)):*
> ```XML
>     /// receiver end's drop status (ie: if the receiver dropped unexpectedly).
>     close_rx: oneshot::Receiver<Result<(), Error>>,
>     disable_eof_check: bool,
> ```

It looks like we already have `close_after_size` on `DropCloserReadHalf`. I think we can use this flag to ensure the read half can get into this configuration.

As for the Writer, would it make more sense to simply add a similar kind of flag check it in`send_eof()` and not emit an error if the flag is set (ie: `set_ignore_eof()`)?
___
*[`util/buf_channel.rs` line 131 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/341#-Nhd5KaaCsju9LItndLG:-Nhd5KaaCsju9LItndLH:bq85xel) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/d8bf8c0670a8171beeecf58b4c1e4c033aa16f4f/util/buf_channel.rs#L131)):*
> ```XML
>     {
>         loop {
>             if let Some(maybe_chunk) = reader.next().await {
> ```

nit: I personally prefer the `match` syntax here, it feels easier to read to me. but just my opinion.


<!-- Sent from Reviewable.io -->

2023-10-25 23:20 UTC, allada requested changes
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/341)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @aaronmondal)



<!-- Sent from Reviewable.io -->

2023-10-26 00:18 UTC, MarcusSorealheis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/341#-:-NhdLCESEaVYm0p8kxHe:bnfp4nl)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @aaronmondal and @allada)



<!-- Sent from Reviewable.io -->

2023-10-26 00:20 UTC, aaronmondal reviewed
@MarcusSorealheis  I agree that we don't want to name this S3. Something like `ObjectStore` or `BlobStore` seems more appropriate and lets us use more vendor-specific libraries to interact with AWS, GCP, Azure and custom solutions like CubeFS, Ceph and Minio.

I'll soon have a new implementation for S3 via the AWS SDK instead of rusoto ready. I still need to look into others. Then we can generalize the current implementation.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/341#-:-NhdKmWvAzjUbMh5RMz2:bskhubw)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @allada)

___
*[`util/buf_channel.rs` line 58 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/341#-Nhd50TZ3A0Ncft8BGYL:-NhdHtidBc-6Mu8-Layu:b-7ltkoe) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/d8bf8c0670a8171beeecf58b4c1e4c033aa16f4f/util/buf_channel.rs#L58)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Why not just add `.disable_eof_check(&mut self)` on the writer?
</blockquote></details>

Done. Yes that's much better :+1:
___
*[`util/buf_channel.rs` line 88 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/341#-Nhd7BfI4JsNT6zJKT4z:-NhdI27pEZlG4xNEtw7T:b69x8kt) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/d8bf8c0670a8171beeecf58b4c1e4c033aa16f4f/util/buf_channel.rs#L88)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

It looks like we already have `close_after_size` on `DropCloserReadHalf`. I think we can use this flag to ensure the read half can get into this configuration.

As for the Writer, would it make more sense to simply add a similar kind of flag check it in`send_eof()` and not emit an error if the flag is set (ie: `set_ignore_eof()`)?
</blockquote></details>

Not sure I understood you correctly here. Is the new version what you envision?
___
*[`util/buf_channel.rs` line 131 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/341#-Nhd5KaaCsju9LItndLG:-NhdI8MfAo3wF09mZVEV:bxr80cu) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/d8bf8c0670a8171beeecf58b4c1e4c033aa16f4f/util/buf_channel.rs#L131)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: I personally prefer the `match` syntax here, it feels easier to read to me. but just my opinion.
</blockquote></details>

That was flagged by clippy::single_match_else I'd prefer the new variant since it reduces indentation.


<!-- Sent from Reviewable.io -->

2023-10-26 00:28 UTC, allada approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/341#-:-NhdNQxH5q5lT4FUwvzG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronmondal)

___
*[`util/buf_channel.rs` line 88 at r1](https://reviewable.io/reviews/TraceMachina/turbo-cache/341#-Nhd7BfI4JsNT6zJKT4z:-NhdN-gd0-iFzMSuvaC5:b-rq7u4t) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/d8bf8c0670a8171beeecf58b4c1e4c033aa16f4f/util/buf_channel.rs#L88)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Not sure I understood you correctly here. Is the new version what you envision?
</blockquote></details>

Yep, this is exactly what I was referring :-) ... To me this is so much easier to read.


<!-- Sent from Reviewable.io -->

2023-10-26 01:09 UTC, merged